# -*- coding: utf-8 -*-
"""Q6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cbNHdiGFi0_HAXxu0LBrC4Tkmt1oDFjG
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_csv('./german_credit_data.csv')

data.info()

data.columns

data.isnull().sum()

data.head()

data=data.drop(columns=['Sex','Job','Housing','Saving accounts','Checking account','Purpose','Unnamed: 0'])

data

for r in data.columns:
    plt.boxplot(data[r])
    plt.title(r)
    plt.show()

def iqr(X):
  Q1=X.quantile(0.25)
  Q3=X.quantile(0.75)
  low_lim =Q1-1.5*(Q3-Q1)
  high_lim =Q3+1.5*(Q3-Q1)
  return low_lim, high_lim

for c in  data.columns:
    l, h= iqr(data[c])
    data = data[(data[c] >= l) & (data[c] <= h)]



for r in data.columns:
    plt.boxplot(data[r])
    plt.title(r)
    plt.show()

